// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using MySpectrumCodingTest.iOS.Security;
using UIKit;
using Xamarin.Essentials;
using iOSSecurity = Security;

namespace MySpectrumCodingTest.iOS.ViewControllers
{
    public partial class LoginViewController : UIViewController
    {
        public LoginViewController(IntPtr handle) : base(handle)
        {
        }
        public LoginViewController() : base(nameof(LoginViewController), null)
        {
        }

        public override async void ViewDidLoad()
        {
            base.ViewDidLoad();
            

            try
            {

                await SecureStorage.SetAsync("Username", "luiseduardohd");
                await SecureStorage.SetAsync("Password", "Password1xyz");
            }
            catch (Exception ex)
            {

            }
            var Username = "";
            var Password = "";
            try
            {
                Username = await SecureStorage.GetAsync("Username");
                Password = await SecureStorage.GetAsync("Password");
            }
            catch (Exception ex)
            {
                
            }

            txtUsername.Text = Username;
            txtPassword.Text = Password;

            
            btnSignIn.TouchUpInside += (object sender, EventArgs e) =>
            {
                this.PerformSegue("LoginPerformed", sender as NSObject);
            };
            btnTroubleSigningIn.TouchUpInside += (object sender, EventArgs e) =>
            {
                //TODO: validation
                //TODO: user can login with username, accounNumber and email.

                this.PerformSegue("LoginPerformed", sender as NSObject);
            };
        }


        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
        }
    }
}